In [2]:
from lir_proteome_screen_pssm import environment as env
import pandas as pd
import lir_proteome_screen_pssm.sequence_utils as seqtools
import re
import numpy as np
import copy
import lir_proteome_screen_pssm.data_loaders as dl

old_regex = "...[FWY]..[LVI]"
new_regex = "...[FWY]..[WFY]"

# preprocessed sequence table from Jen

In [14]:
rename_dict = {
    "first_4_residues": "4mer",
    "first_6_residues": "6mer",
    "first_8_residues": "8mer",
    "first_14_residues": "14mer",
    "first_7_residues": "7mer",
    "first_5_residues": "5mer",
}

screen_df = pd.read_csv(env.RAWFILEPATHS.screening_hits_table)
screen_df = screen_df.rename(columns=rename_dict)
assert all(
    [len(s) == 7 for s in screen_df["7mer"].tolist()]
), "All binders should be 7 residues long"
assert all(
    screen_df["7mer"].str.contains('-') == False
), "No 7mers should contain gaps"

screen_binders_df = screen_df[screen_df["Bind/Nonbind"] == "Bind"].copy()
screen_binders_df["true label"] = 1
screen_binders_df = screen_binders_df.sort_values(by="avg_z_score", ascending=False)
screen_nonbinders_df = screen_df[screen_df['Bind/Nonbind'] == 'Nonbind'].copy()
screen_nonbinders_df["true label"] = 0
print(len(screen_binders_df))
a = set(screen_binders_df["7mer"].to_list())

297

In [15]:
screen_binders_df[['ID', 'Input Count', 'avg_z_score', '7mer']].to_csv("./09_binders_from_Jen.csv", index=False)

# from all data to preprocessed binders (a double check)

In [ ]:
full_data_table = pd.read_csv(env.RAWFILEPATHS.full_screening_table, sep='\t')
screen_binders_from_raw = full_data_table[full_data_table['avg_z_score'] >= 1.7].copy()
screen_binders_from_raw = screen_binders_from_raw[screen_binders_from_raw['Input Count'] >= 10].copy()
# regex extract 7mer from 7mer column
# only keep 

def get_regex_matches(s: pd.Series, regex: str):
    matches = list(seqtools.get_regex_matches(regex, s["ID"]))
    # if len(matches) == 0:
    #     return
    return matches

print(len(screen_binders_from_raw))
# REGEX = seqtools.regex2overlapping("...[FWY]..[ILVWFY]")
# REGEX = "...[FWY]..[ILVWFY]"
REGEX = "[FWY]..[ILVWFY]"
screen_binders_from_raw["regex_matches"] = screen_binders_from_raw.apply(get_regex_matches, axis=1, regex=REGEX)
screen_binders_from_raw["num_regex_matches"] = screen_binders_from_raw["regex_matches"].apply(lambda x: len(x))
screen_binders_from_raw["num_regex_matches"].value_counts()
df_multi = screen_binders_from_raw[screen_binders_from_raw["num_regex_matches"] > 1].copy()
df_multi = df_multi.explode("regex_matches")
df_single = screen_binders_from_raw[screen_binders_from_raw["num_regex_matches"] == 1].copy()
df_single["regex_matches"] = df_single["regex_matches"].apply(lambda x: x[0])
screen_binders_from_raw = pd.concat([df_multi, df_single])
screen_binders_from_raw[["7mer", "motif_start", "motif_end"]] = pd.DataFrame(
    screen_binders_from_raw["regex_matches"].tolist(), index=screen_binders_from_raw.index
)
screen_binders_from_raw = screen_binders_from_raw.sort_values(by="avg_z_score", ascending=False)
print(len(screen_binders_from_raw))
b = set(screen_binders_from_raw["7mer"].to_list())

420
307

In [19]:
screen_binders_from_raw[['ID', 'Input Count', 'avg_z_score', '7mer']].to_csv("./09_binders_from_Jackson.csv", index=False)

In [7]:
print(len(a), len(b))

283 260

In [8]:
screen_binders_from_raw[screen_binders_from_raw['7mer'].isin(b.difference(a))]

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score,regex_matches,num_regex_matches,7mer,motif_start,motif_end
5,5,IWYWSDEFGSWQEYGRQGTVTL,0,5.208992,9.572567,11.569644,12.334340,12.643501,319,6432,...,51.2,3.345774,3.710809,4.088600,3.72,"(SDEFGSW, 4, 10)",1,SDEFGSW,4,10
20,23,YLGQLEHEDIDTSADAVEDLTEAEWEDLTQQYYSLV,0,5.857058,9.449375,11.147782,11.561737,11.270682,124,3918,...,80.1,3.165840,3.389663,3.513537,3.36,"(TQQYYSL, 28, 34)",2,TQQYYSL,28,34
27,30,LDGTAVENIETFQTEDHTFDEYTEELDCWVVWE,0,5.473140,9.478454,10.950355,11.217866,11.141941,42,1017,...,53.1,3.081632,3.246726,3.459609,3.26,"(DHTFDEY, 15, 21)",2,DHTFDEY,15,21
27,30,LDGTAVENIETFQTEDHTFDEYTEELDCWVVWE,0,5.473140,9.478454,10.950355,11.217866,11.141941,42,1017,...,53.1,3.081632,3.246726,3.459609,3.26,"(LDCWVVW, 25, 31)",2,LDCWVVW,25,31
41,45,NRVTVYEYDTREDQWINIGTI,0,4.826754,8.687136,10.142549,10.645705,10.688468,200,3094,...,49.7,2.737083,3.008897,3.269653,3.01,"(EDQWINI, 11, 17)",1,EDQWINI,11,17
48,53,MFHKAEELFSKTTNNEVDDMDTSDTQWGWF,0,4.941442,8.601221,10.013964,10.283439,10.441986,68,1139,...,66.6,2.682238,2.858315,3.166403,2.90,"(DTQWGWF, 23, 29)",1,DTQWGWF,23,29
54,59,ESSTEWDLDSFSELDSESGSSSSFSDDEVWVQVAPQ,0,6.625375,9.298088,10.101788,10.390150,9.487462,11,592,...,70.1,2.719697,2.902671,2.766561,2.80,"(LDSFSEL, 7, 13)",2,LDSFSEL,7,13
66,71,VTPDSGYSSAHAEATYEEDWEVFDPYYFIKRPATD,0,5.932803,8.641368,9.730574,9.958704,9.744875,60,1998,...,67.4,2.561365,2.723333,2.874389,2.72,"(EEDWEVF, 16, 22)",1,EEDWEVF,16,22
89,94,IWYWSDEFGSWQEYGRQGTVHPVTTVSSSDVEKAYL,0,6.032177,8.032407,9.444030,9.577986,9.270664,169,6029,...,79.7,2.439147,2.565080,2.675746,2.56,"(SDEFGSW, 4, 10)",1,SDEFGSW,4,10
113,118,KEELVMSSLKRLNSYLSLPKFRSFRTY,0,5.230196,8.516249,9.457672,9.272525,8.409952,13,266,...,22.3,2.444966,2.438110,2.315201,2.40,"(FRSFRTY, 20, 26)",2,FRSFRTY,20,26
112,117,SVATEESADPLSEDDFETFYEIWEKFDPDATQFIE,0,6.099726,8.416112,9.101393,9.341787,8.731880,13,486,...,73.6,2.293004,2.466900,2.450054,2.40,"(YEIWEKF, 19, 25)",2,YEIWEKF,19,25
127,134,MATRNPPPQDYESDDDSYEVLDLTEYARRHQWWNRV,0,6.204448,8.118237,9.043416,8.970077,8.145157,246,9889,...,87.0,2.268276,2.312392,2.204280,2.26,"(HQWWNRV, 29, 35)",2,HQWWNRV,29,35
230,237,YLKYINLKASEKLDYITYLSI,0,4.723350,7.841202,8.116092,8.243861,7.788464,10,144,...,43.1,1.872749,2.010527,2.054864,1.98,"(YLKYINL, 0, 6)",2,YLKYINL,0,6
415,422,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,28,1042,...,72.4,1.663313,1.808750,1.617183,1.70,"(SGAYPDL, 27, 33)",1,SGAYPDL,27,33

In [9]:
screen_binders_df[screen_binders_df['7mer'].isin(a.difference(b))]

,ID,Position,Hit,Length,Input Count,ER 0,ER 1,ER 3,4,5,...,24_mer,12_mer,sequence_length,nonLIR_6,nonLIR_8,nonLIR_7,nonLIR_5,7mer,5mer,true label
5,EDWDMLDVDEDEKLTGEEEFELLLVRLV,31,NaN,28,12,NaN,NaN,NaN,11.862116,12.408549,...,GGSGIPLREDWDMLDVDEDEKLTG,LREDWDMLDVDE,24,EDWDML,LREDWDML,REDWDML,DWDML,REDWDML,DWDML,1
13,DVWEILRRHRHLSTSASPSSTASLTCAAC,31,NaN,29,24,NaN,NaN,NaN,11.500042,12.169792,...,GGSGIPLRDVWEILRRHRHLSTSA,LRDVWEILRRHR,24,DVWEIL,LRDVWEIL,RDVWEIL,VWEIL,RDVWEIL,VWEIL,1
18,KLEVPTGPEVQTPKPSDADWDDLWTSLMGGGI,52,NaN,32,20,NaN,NaN,NaN,11.253341,11.691843,...,KPSDADWDDLWTSLMGGGI-----,WDDLWTSLMGGG,24,DLWTSL,WDDLWTSL,DDLWTSL,LWTSL,DDLWTSL,LWTSL,1
21,PYDSYNPSVLRGPLLGHTDAVWGLL,30,NaN,25,30,NaN,NaN,NaN,10.908996,11.388002,...,GGGSGIPLRPYDSYNPSVLRGPLL,PLRPYDSYNPSV,24,RPYDSY,PLRPYDSY,LRPYDSY,PYDSY,LRPYDSY,PYDSY,1
29,EDWDMLDVDEDEKLTGEEEFELLAGPLGLNDRRIVP,31,NaN,36,546,NaN,NaN,NaN,10.764586,11.127201,...,GGSGIPLREDWDMLDVDEDEKLTG,LREDWDMLDVDE,24,EDWDML,LREDWDML,REDWDML,DWDML,REDWDML,DWDML,1
37,FPPHQQHPQFNQPPHPHNFNRFPPRFMQDDSATAA,47,NaN,35,12,NaN,NaN,NaN,10.208153,11.042227,...,QFNQPPHPHNFNRFPPRFMQDDSA,HPHNFNRFPPRF,24,HNFNRF,HPHNFNRF,PHNFNRF,NFNRF,PHNFNRF,NFNRF,1
48,MNNDKHCFECYGYDIIIDES,41,NaN,20,51,NaN,NaN,NaN,10.059859,10.532193,...,NDKHCFECYGYDIIIDES------,ECYGYDIIIDES,24,YGYDII,ECYGYDII,CYGYDII,GYDII,CYGYDII,GYDII,1
49,ESTQHILNPNTSLNSNNFQILHSSHPQGNYSNSKLS,46,NaN,36,622,NaN,NaN,NaN,10.230125,10.488100,...,NPNTSLNSNNFQILHSSHPQGNYS,NSNNFQILHSSH,24,NNFQIL,NSNNFQIL,SNNFQIL,NFQIL,SNNFQIL,NFQIL,1
55,HSVVPLLDSYDLLSYDDLSH,43,NaN,20,22,NaN,NaN,NaN,10.242322,10.303895,...,PLLDSYDLLSYDDLSH--------,DLLSYDDLSH--,24,LSYDDL,DLLSYDDL,LLSYDDL,SYDDL,LLSYDDL,SYDDL,1
74,TEEQLKEKFPEADPYEIIESFNVVAKEVFVVLF,49,NaN,33,37,NaN,NaN,NaN,10.114429,9.745663,...,EADPYEIIESFNVVAKEVFVVLF-,IIESFNVVAKEV,24,ESFNVV,IIESFNVV,IESFNVV,SFNVV,IESFNVV,SFNVV,1
103,QFSAGGCTFDDGPGACDYHQDLYDDFEWVHVSAQEP,56,NaN,36,122,NaN,NaN,NaN,9.278644,9.426639,...,YHQDLYDDFEWVHVSAQEPRIARG,DDFEWVHVSAQE,24,FEWVHV,DDFEWVHV,DFEWVHV,EWVHV,DFEWVHV,EWVHV,1
105,PLYMNLQKLLEMVREDARRTVTIENGMQRKAPSLLS,31,NaN,36,11,NaN,NaN,NaN,9.205766,9.337683,...,GGSGIPLRPLYMNLQKLLEMVRED,LRPLYMNLQKLL,24,PLYMNL,LRPLYMNL,RPLYMNL,LYMNL,RPLYMNL,LYMNL,1
106,FFQNVIKETRAEPKKVTSGSSTLFWAI,30,NaN,27,14,NaN,NaN,NaN,9.049891,9.404797,...,GGGSGIPLRFFQNVIKETRAEPKK,PLRFFQNVIKET,24,RFFQNV,PLRFFQNV,LRFFQNV,FFQNV,LRFFQNV,FFQNV,1
115,LFHHLRIHTGEKPYQCNQCNKSFSRR,30,NaN,26,12,NaN,NaN,NaN,8.929293,9.212152,...,GGGSGIPLRLFHHLRIHTGEKPYQ,PLRLFHHLRIHT,24,RLFHHL,PLRLFHHL,LRLFHHL,LFHHL,LRLFHHL,LFHHL,1
118,SVATEESADPLSEDDFETFYEIWEKFDPDATQFIE,48,NaN,35,13,NaN,NaN,NaN,9.101393,9.341787,...,PLSEDDFETFYEIWEKFDPDATQF,FETFYEIWEKFD,24,TFYEIW,FETFYEIW,ETFYEIW,FYEIW,ETFYEIW,FYEIW,1
120,KEELVMSSLKRLNSYLSLPKFRSFRTY,49,NaN,27,13,NaN,NaN,NaN,9.457672,9.272525,...,RLNSYLSLPKFRSFRTY-------,SLPKFRSFRTY-,24,PKFRSF,SLPKFRSF,LPKFRSF,KFRSF,LPKFRSF,KFRSF,1
122,ESTQHILNPNTSLNSNNFQILHSSHPQANYSNSKLS,46,NaN,36,57,NaN,NaN,NaN,9.014916,8.964225,...,NPNTSLNSNNFQILHSSHPQANYS,NSNNFQILHSSH,24,NNFQIL,NSNNFQIL,SNNFQIL,NFQIL,SNNFQIL,NFQIL,1
123,FIAIKSIDKSNLTSKVSNIAQVYPSSKS,29,NaN,28,21,NaN,NaN,NaN,8.904840,8.953690,...,SGGGSGIPLRFIAIKSIDKSNLTS,IPLRFIAIKSID,24,LRFIAI,IPLRFIAI,PLRFIAI,RFIAI,PLRFIAI,RFIAI,1
125,KLEVPTGPEVQTPKPSDADWDDLWDQFDERRYLNAI,52,NaN,36,68,NaN,NaN,NaN,9.016169,9.221551,...,KPSDADWDDLWDQFDERRYLNAIR,WDDLWDQFDERR,24,DLWDQF,WDDLWDQF,DDLWDQF,LWDQF,DDLWDQF,LWDQF,1
135,FVRFHEDGARTKALLGKLFAAMNL,29,NaN,24,16,NaN,NaN,NaN,8.989035,8.686083,...,SGGGSGIPLRFVRFHEDGARTKAL,IPLRFVRFHEDG,24,LRFVRF,IPLRFVRF,PLRFVRF,RFVRF,PLRFVRF,RFVRF,1
139,PALFKSYAEYGHFVHSYCSFGSSC,38,NaN,24,10,NaN,NaN,NaN,8.999683,8.420739,...,RPALFKSYAEYGHFVHSYCSFGSS,SYAEYGHFVHSY,24,AEYGHF,SYAEYGHF,YAEYGHF,EYGHF,YAEYGHF,EYGHF,1
149,KPVPQDTKFIHTKANRFEEVAWSKYNPRDHSTFTS,50,NaN,35,13,NaN,NaN,NaN,8.242053,8.589715,...,TKANRFEEVAWSKYNPRDHSTFTS,EEVAWSKYNPRD,24,VAWSKY,EEVAWSKY,EVAWSKY,AWSKY,EVAWSKY,AWSKY,1
162,FPQIVNSNPLTEAFRVNWLSGLL,29,NaN,23,12,NaN,NaN,NaN,8.556076,8.501659,...,SGGGSGIPLRFPQIVNSNPLTEAF,IPLRFPQIVNSN,24,LRFPQI,IPLRFPQI,PLRFPQI,RFPQI,PLRFPQI,RFPQI,1
165,FIAIKSIDKSNLTSKVSNIANNFVYPSSKS,29,NaN,30,23,NaN,NaN,NaN,8.358558,8.495945,...,SGGGSGIPLRFIAIKSIDKSNLTS,IPLRFIAIKSID,24,LRFIAI,IPLRFIAI,PLRFIAI,RFIAI,PLRFIAI,RFIAI,1
169,MWNIFSKAGYGSLRVISSSGFSSWM,30,NaN,25,18,NaN,NaN,NaN,8.064223,8.331734,...,GGGSGIPLRMWNIFSKAGYGSLRV,PLRMWNIFSKAG,24,RMWNIF,PLRMWNIF,LRMWNIF,MWNIF,LRMWNIF,MWNIF,1
173,SQSLTPQQQPQYNLPERDKQLLFSEYNFEDLSASFR,56,NaN,36,228,NaN,NaN,NaN,8.573685,8.270033,...,DKQLLFSEYNFEDLSASFRRIARG,SEYNFEDLSASF,24,YNFEDL,SEYNFEDL,EYNFEDL,NFEDL,EYNFEDL,NFEDL,1
187,YVTWKLSGLPKHRVIGSGCNLDCSFSLPYG,29,NaN,30,18,NaN,NaN,NaN,7.649185,8.426891,...,SGGGSGIPLRYVTWKLSGLPKHRV,IPLRYVTWKLSG,24,LRYVTW,IPLRYVTW,PLRYVTW,RYVTW,PLRYVTW,RYVTW,1
191,YLKYINLKASEKLDYITYLSI,29,NaN,21,10,NaN,NaN,NaN,8.116092,8.243861,...,SGGGSGIPLRYLKYINLKASEKLD,IPLRYLKYINLK,24,LRYLKY,IPLRYLKY,PLRYLKY,RYLKY,PLRYLKY,RYLKY,1
196,TFKAAVSNFTTFKAAGIFRTLKFQQYSV,51,NaN,28,20,NaN,NaN,NaN,7.993608,8.077851,...,KAAGIFRTLKFQQYSV--------,RTLKFQQYSV--,24,LKFQQY,RTLKFQQY,TLKFQQY,KFQQY,TLKFQQY,KFQQY,1
198,EIYPLITTVSRVSPCCRFLDAA,31,NaN,22,11,NaN,NaN,NaN,8.137286,8.390150,...,GGSGIPLREIYPLITTVSRVSPCC,LREIYPLITTVS,24,EIYPLI,LREIYPLI,REIYPLI,IYPLI,REIYPLI,IYPLI,1
199,YMRLGSTKLSDKDKAVGISTLSSTRC,29,NaN,26,33,NaN,NaN,NaN,8.054824,7.880476,...,SGGGSGIPLRYMRLGSTKLSDKDK,IPLRYMRLGSTK,24,LRYMRL,IPLRYMRL,PLRYMRL,RYMRL,PLRYMRL,RYMRL,1
202,FQNIMRRTAQAVMNNTVTSSVVYPC,29,NaN,25,12,NaN,NaN,NaN,8.549190,7.627190,...,SGGGSGIPLRFQNIMRRTAQAVMN,IPLRFQNIMRRT,24,LRFQNI,IPLRFQNI,PLRFQNI,RFQNI,PLRFQNI,RFQNI,1
207,LFKPLGPIIIDGKDQKSEPPTSLPQNVNV,30,NaN,29,16,NaN,NaN,NaN,7.674720,7.501659,...,GGGSGIPLRLFKPLGPIIIDGKDQ,PLRLFKPLGPII,24,RLFKPL,PLRLFKPL,LRLFKPL,LFKPL,LRLFKPL,LFKPL,1
226,AWGTWGPGAEPEDWGILGREEARTTPGREEARAILD,30,NaN,36,103,NaN,NaN,NaN,8.118587,7.933155,...,GGGSGIPLRAWGTWGPGAEPEDWG,PLRAWGTWGPGA,24,RAWGTW,PLRAWGTW,LRAWGTW,AWGTW,LRAWGTW,AWGTW,1
233,DYTSVMHYSKLHSKMVQSRRLSHVSQTLRM,30,NaN,30,27,NaN,NaN,NaN,8.068510,8.068699,...,GGGSGIPLRDYTSVMHYSKLHSKM,PLRDYTSVMHYS,24,RDYTSV,PLRDYTSV,LRDYTSV,DYTSV,LRDYTSV,DYTSV,1
237,IWQFSSLFSKIKSWEFNEVTSMSST,36,NaN,25,31,NaN,NaN,NaN,7.825743,7.895386,...,PLRIWQFSSLFSKIKSWEFNEVTS,FSSLFSKIKSWE,24,SLFSKI,FSSLFSKI,SSLFSKI,LFSKI,SSLFSKI,LFSKI,1
250,EYFAALMTTMEAVESPESLAPLLTC,31,NaN,25,11,NaN,NaN,NaN,7.359679,7.975113,...,GGSGIPLREYFAALMTTMEAVESP,LREYFAALMTTM,24,EYFAAL,LREYFAAL,REYFAAL,YFAAL,REYFAAL,YFAAL,1
284,GFWTGLGTGGILGYLFGSNRAATPFSDSWYYPSYPP,31,NaN,36,23,NaN,NaN,NaN,7.596718,7.219105,...,GGSGIPLRGFWTGLGTGGILGYLF,LRGFWTGLGTGG,24,GFWTGL,LRGFWTGL,RGFWTGL,FWTGL,RGFWTGL,FWTGL,1
292,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,48,NaN,33,407,NaN,NaN,NaN,8.140802,7.387363,...,TDAEFVILLLFLLLLFFFFRASFA,ILLLFLLLLFFF,24,LLFLLL,ILLLFLLL,LLLFLLL,LFLLL,LLLFLLL,LFLLL,1

In [10]:
print(len(a.difference(b)))
print(len(b.difference(a)))

36
13

In [11]:
full_data_table[full_data_table['ID'].isin(screen_binders_df['ID'].to_list())]

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,415,MARVPLTFSDVAIASLRRSGNI,0,4.497790,6.555125,7.338737,7.601655,7.303037,19,234,...,1.0,13.0,1.0,13.0,5.000000e-03,30.4,1.541188,1.743582,1.851523,1.71
413,420,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,0,4.039740,7.065926,7.296732,7.828102,7.030019,29,260,...,1.0,27.0,842.0,868.0,3.130000e-11,54.3,1.523272,1.837709,1.737157,1.70
417,424,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,407,4788,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
418,425,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,48,278,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
419,426,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,11,197,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [12]:
full_data_table[full_data_table['ID']=='DIDNFDIDDFDDDDDWEDICII']

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.9,23.1,3.574377,4.082822,4.670163,4.11

In [14]:
screen_binders_from_raw[screen_binders_from_raw['ID']=='DIDNFDIDDFDDDDDWEDICII']

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score,regex_matches,num_regex_matches,7mer,motif_start,motif_end
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,23.1,3.574377,4.082822,4.670163,4.11,"(DDDWEDI, 12, 18)",1,DDDWEDI,12,18

# junk