In [4]:
import pandas as pd
import lir_proteome_screen_pssm.environment as env

In [2]:
import lir_proteome_screen_pssm.data_loaders as dl

pst = dl.get_processed_sequence_tables()
pst.ilir_binders

,_UNIPROT ID,_UNIPROT ACC,6mer,_Position,_Verified,_cLIR,_xLIR,_Anchor,_PSSM score (e-value),_Species,_header,_full_length_seq,_ids_equal,_start_position,_n_matches,7mer
0,NaN,O75143,DDFVMI,442‚Äì447,Yes,Yes,Yes,Yes,20 (8.4e-03),Human,sp|O75143|ATG13_HUMAN Autophagy-related protei...,METDLNSQDRKDLDKFIKFFALKTVQVIVQARLGEKICTRSSSSPT...,True,441,1,HDDFVMI
1,Atg1_YEAST,P53104,REYVVV,427‚Äì432,Yes,No,Yes,Yes,14 (5.7e-02),Yeast,sp|P53104|ATG1_YEAST Serine/threonine-protein ...,MGDIKNKDHTTSVNHNLMASAGNYTAEKEIGKGSFATVYRGHLTSD...,True,426,1,EREYVVV
2,Atg32_YEAST,P40458,GSWQAI,84‚Äì89,Yes,No,Yes,Yes,17 (2.2e-02),Yeast,sp|P40458|ATG32_YEAST Autophagy-related protei...,MVLEYQQREGKGSSSKSMPPDSSSTTIHTCSEAQTGEDKGLLDPHL...,True,83,1,SGSWQAI
3,ATG4B_HUMAN** [MM],Q9Y4P1,LTYDTL,6‚Äì11,Yes,No,Yes,No,12 (1.1e-01),Human,sp|Q9Y4P1|ATG4B_HUMAN Cysteine protease ATG4B ...,MDAATLTYDTLRFAEFEDFPETSEPVWILGRKYSIFTEKDEILSDV...,True,5,1,TLTYDTL
4,Atg19_YEAST,P35193,LTWEEL,410‚Äì415,Yes,No,Yes,No,18 (1.6e-02),Yeast,sp|P35193|ATG19_YEAST Autophagy-related protei...,MNNSKTNQQMNTSMGYPLTVYDECNKFQLIVPTLDANIMLWCIGQL...,True,409,1,ALTWEEL
5,Atg3_YEAST,P40344,GDWEDL,268‚Äì273,Yes,No,Yes,No,22 (4.4e-03),Yeast,sp|P40344|ATG3_YEAST Autophagy-related protein...,MIRSTLSSWREYLTPITHKSTFLTTGQITPEEFVQAGDYLCHMFPT...,True,267,1,VGDWEDL
6,BNI3L_HUMAN,O60238,SSWVEL,34‚Äì39,Yes,No,Yes,Yes,20 (8.4e-03),Human,sp|O60238|BNI3L_HUMAN BCL2/adenovirus E1B 19 k...,MSSHLVEPPPPLHNNNNNCEENEQSLPPPAGLNSSWVELPMNSSNG...,True,33,1,NSSWVEL
7,NaN,P27797,DDWDFL,198‚Äì203,Yes,Yes,Yes,Yes,26 (1.2e-03),Human,sp|P27797|CALR_HUMAN Calreticulin OS=Homo sapi...,MLLSVPLLLGLLGLAVAEPAVYFKEQFLDGDGWTSRWIESKHKSDF...,True,197,1,EDDWDFL
8,NaN,P22681,FGWLSL,800‚Äì805,Yes,No,Yes,Yes,18 (1.6e-02),Human,sp|P22681|CBL_HUMAN E3 ubiquitin-protein ligas...,MAGNVKKSSGAGGGSGSGGSGSGGLIGLMKDAFQPHHHHHHHLSPH...,True,799,1,SFGWLSL
9,FUND1_HUMAN,Q8IVP5,DSYEVL,16‚Äì21,Yes,Yes,Yes,No,16 (3.0e-02),Human,sp|Q8IVP5|FUND1_HUMAN FUN14 domain-containing ...,MATRNPPPQDYESDDDSYEVLDLTEYARRHQWWNRVFGHSSGPMVE...,True,15,1,DDSYEVL
10,OPTN_HUMAN,Q96CV9,DSFVEI,176‚Äì181,Yes,Yes,Yes,Yes,15 (4.2e-02),Human,sp|Q96CV9|OPTN_HUMAN Optineurin OS=Homo sapien...,MSHQPLSCLTEKEDSPSESTGNGPPHLAHPNLDTFTPEELLQQMKE...,True,175,1,EDSFVEI
11,NaN,Q8MQJ7,DDFVLV,389‚Äì394,Yes,Yes,Yes,Yes,17 (2.2e-02),Drosophila,"tr|Q8MQJ7|Q8MQJ7_DROME Autophagy-related 1, is...",MNIVGEYEYSSKDMLGHGAFAVVYKGRHRKKHMPVAIKCITKKGQL...,True,388,1,SDDFVLV
12,NaN,Q9SB64,SEWDPI,659‚Äì664,Yes,No,Yes,No,20 (8.4e-03),Arabidopsis,sp|Q9SB64|NBR1_ARATH Protein NBR1 homolog OS=A...,MESTANALVVKVSYGGVLRRFRVPVKANGQLDLEMAGLKEKIAALF...,True,658,1,VSEWDPI
13,RBCC1_HUMAN,Q8TDY2,FDFETI,700‚Äì705,Yes,No,Yes,Yes,17 (2.2e-02),Human,sp|Q8TDY2|RBCC1_HUMAN RB1-inducible coiled-coi...,MKLYVFLVNTGTTLTFDTELTVQTVADLKHAIQSKYKIAIQHQVLV...,True,699,1,TFDFETI
14,SQSTM_HUMAN** [LL],Q13501,DDWTHL,336‚Äì341,Yes,No,Yes,Yes,24 (2.3e-03),Human,sp|Q13501|SQSTM_HUMAN Sequestosome-1 OS=Homo s...,MASLTVKAYLLGKEDAAREIRRFSFCCSPEPEAEAEAAAGPGPCER...,True,335,1,DDDWTHL
15,STBD1_HUMAN** [LN],O95210,EEWEMV,201‚Äì206,Yes,Yes,Yes,No,21 (6.1e-03),Human,sp|O95210|STBD1_HUMAN Starch-binding domain-co...,MGAVWSALLVGGGLAGALFVWLLRGGPGDTGKDGDAEQEKDAPLGG...,True,200,1,HEEWEMV
16,T53I1_HUMAN,Q96A56,DEWILV,29‚Äì34,Yes,Yes,Yes,Yes,20 (8.4e-03),Human,sp|Q96A56|T53I1_HUMAN Tumor protein p53-induci...,MFQRLNKMFVGEVSSSSNQEPEFNEKEDDEWILVDFIDTCTGFSAE...,True,28,1,DDEWILV
17,NaN,Q3MII6,EDWDII,134‚Äì139,Yes,Yes,Yes,No,24 (2.3e-03),Human,sp|Q3MII6|TBC25_HUMAN TBC1 domain family membe...,MATASGASDLSGSGAPPPGVGAQAAAAAEEEEREVVRVRVKKCESF...,True,133,1,LEDWDII
18,TBCD5_HUMAN,Q92609,KEWEEL,57‚Äì62,Yes,No,Yes,No,20 (8.4e-03),Human,sp|Q92609|TBCD5_HUMAN TBC1 domain family membe...,MYHSLSETRHPLQPEEQEVGIDPLSSYSNKSGGDSNKNGRRTSSTL...,True,56,1,RKEWEEL
19,NaN,Q92609,SGFTIV,785‚Äì790,Yes,No,Yes,Yes,11 (1.5e-01),Human,sp|Q92609|TBCD5_HUMAN TBC1 domain family membe...,MYHSLSETRHPLQPEEQEVGIDPLSSYSNKSGGDSNKNGRRTSSTL...,True,784,1,DSGFTIV
20,T53I2_HUMAN,Q8IXH6,DGWLII,33‚Äì38,Yes,No,Yes,Yes,21 (6.1e-03),Human,sp|Q8IXH6|T53I2_HUMAN Tumor protein p53-induci...,MFQRLSSLFFSTPSPPEDPDCPRAFVSEEDEVDGWLIIDLPDSYAA...,True,32,1,VDGWLII
21,ULK1_HUMAN,O75385,DDFVMV,355‚Äì360,Yes,Yes,Yes,Yes,19 (1.2e-02),Human,sp|O75385|ULK1_HUMAN Serine/threonine-protein ...,MEPGRGGTETVGKFEFSRKDLIGHGAFAVVFKGRHREKHDLEVAVK...,True,354,1,TDDFVMV
22,ULK2_HUMAN,Q8IYT8,DDFVLV,351‚Äì356,Yes,Yes,Yes,Yes,17 (2.2e-02),Human,sp|Q8IYT8|ULK2_HUMAN Serine/threonine-protein ...,MEVVGDFEYSKRDLVGHGAFAVVFRGRHRQKTDWEVAIKSINKKNL...,True,350,1,TDDFVLV
23,CLH1_HUMAN,Q00610,PDWIFL,512‚Äì517,Yes,No,Yes,No,22 (4.4e-03),Human,sp|Q00610|CLH1_HUMAN Clathrin heavy chain 1 OS...,MAQILPIRFQEHLQLQNLGINPANIGFSTLTMESDKFICIREKVGE...,True,511,1,TPDWIFL
24,DVL2_HUMAN,O14641,RMWLKI,442‚Äì447,Yes,No,Yes,No,18 (1.6e-02),Human,sp|O14641|DVL2_HUMAN Segment polarity protein ...,MAGSSTGGGGVGETKVIYHLDEEETPYLVKIPVPAERITLGDFKSV...,True,441,1,DRMWLKI
25,NaN,Q9BQS8,AVFDII,1278‚Äì1283,Yes,No,Yes,Yes,8 (3.9e-01),Human,sp|Q9BQS8|FYCO1_HUMAN FYVE and coiled-coil dom...,MASTNAESQLQRIIRDLQDAVTELSKEFQEAGEPITDDSTSLHKFS...,True,1277,1,DAVFDII
26,NaN,Q14596,EDYIII,730‚Äì735,Yes,Yes,Yes,Yes,17 (2.2e-02),Human,sp|Q14596|NBR1_HUMAN Next to BRCA1 gene 1 prot...,MEPQVTLNVTFKNEIQSFLVSDPENTTWADIEAMVKVSFDLNTIQI...,True,729,1,SEDYIII

In [8]:
lc = pd.read_csv(env.RAW_DATA_DIR / "LIRcentral - Data export.csv")

In [11]:
lc

,Unnamed: 0,Species,UNIPROT ACC,UNIPROT ID,Protein name,Motif type,Up-stream,Motif,Down-stream,Start position,End position,(-2)LIR PSSM score,ExperimentallyVerified(FunctionalYES/NO),Ref.
0,NaN,Homo sapiens,A0A3Q9JIX6,A0A3Q9JIX6_HUMAN,E2F transcription factor 3 isoform d,Y LIR,FLLWPPQPTS,YSRL,RTKFLPT,160,163,7.0,YES,Ref.
1,NaN,Homo sapiens,B9EIS5,B9EIS5_HUMAN,PCM1 protein,F LIR,NISQKSDEED,FVKV,EDLPLKLTIY,1955,1958,15.0,YES,Ref.
2,NaN,Homo sapiens,O14641,DVL2_HUMAN,Segment polarity protein dishevelled homolog D...,W LIR,ESGLEVRDRM,WLKI,TIPNAFLGSD,444,447,18.0,YES,Ref.
3,NaN,Homo sapiens,O15040,TCPR2_HUMAN,Tectonin beta-propeller repeat-containing prot...,W LIR,MPHPEDLEDE,WEVI,NaN,1408,1411,23.0,YES,Ref.
4,NaN,Homo sapiens,O15111,IKKA_HUMAN,Inhibitor of nuclear factor kappa-B kinase sub...,W LIR,EQGNSMMNLD,WSWL,TE,740,743,15.0,YES,Ref.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,NaN,Homo sapiens,Q96RF0,SNX18_HUMAN,Sorting nexin-18,Non canonical LIR,YQASQGSDDD,WDDEW,DDSSTVADEP,154,158,NaN,YES,Ref.
164,NaN,Homo sapiens,Q9BYX2,TBD2A_HUMAN,TBC1 domain family member 2A,Non canonical LIR,QARNCQVESK,YLAGL,RRLQEALGDE,510,514,NaN,YES,Ref.
165,NaN,Homo sapiens,Q9BYX2,TBD2A_HUMAN,TBC1 domain family member 2A,Non canonical LIR,YWLQQLQMKR,WEFHN,SPPAPPATPD,142,146,NaN,YES,Ref.
166,NaN,Homo sapiens,Q9GZZ9,UBA5_HUMAN,Ubiquitin-like modifier-activating enzyme 5,Non canonical LIR,EEEIIHEDNE,WGIELV,SEVSEEELKN,341,346,NaN,YES,Ref.
167,NaN,Homo sapiens,Q9P1Z2,CACO1_HUMAN,Calcium-binding and coiled-coil domain-contain...,Non canonical LIR,LEEADGGSDI,LVV,VPKATVLQNQ,140,142,NaN,YES,NaN

In [12]:
lc["UNIPROT ACC"].isin(pst.ilir_binders["_UNIPROT ACC"]).sum()

23

In [20]:

lc["Up-stream"] = lc["Up-stream"].fillna("")
lc["Down-stream"] = lc["Down-stream"].fillna("")
lc["Motif"] = lc["Motif"].fillna("")
lc["motif_start_in_hit"] = lc["Up-stream"].str.len()
lc["len_downstream"] = lc["Down-stream"].str.len()
lc["len_motif"] = lc["Motif"].str.len()


def build_7mer(row: pd.Series):
    return row["Up-stream"][-3:] + row["Motif"]


lc["full_seq"] = lc.apply(build_7mer, axis=1)

In [24]:
lc['full_seq'].isin(pst.ilir_binders['7mer']).sum()

21

In [19]:
lcaug = dl.get_test_sets(version="v2").lir_central_augmented
lcaug[lcaug["UNIPROT_ACC"].isin(pst.ilir_binders["_UNIPROT ACC"])]

,7mer,true label,UNIPROT_ACC,UNIPROT_NAME,Protein name,_Motif type,_Up-stream,_Motif,_Down-stream,_Start position,_End position,_Combined
73,LPMFELV,1,Q9Y4P1,ATG4B_HUMAN,Cysteine protease ATG4B,F LIR,LSLLGGALPM,FELV,ELQPSHLACP,349.0,352.0,LSLLGGALPMFELV

In [22]:
lcaug['7mer'].isin(pst.ilir_binders['7mer']).sum()

0